### PR TITLE
feat: support 3rd party plugins/presets

### PR DESCRIPTION
**Pull request by JounQin**
work on https://github.com/ai/size-limit/issues/291#issuecomment-1184607227

cc @ai

### CODE REVIEW

**Comment by JounQin** [comment]
The CI on master branch seems to be broken

https://github.com/ai/size-limit/runs/7342646178?check_suite_focus=true

**Comment by ai** [comment]
Yes, Jest became unstable

**Comment by ai** [comment]
I finally fixed CI!

**Comment by ai** [comment]
The fix was released in 8.0.

**Comment by JounQin** [comment]
Thanks for merging!

**Pull request merged**
