### PR TITLE
Check on CI mutation for yarn.lock

### PR DESCRIPTION
**Pull request by pustovalov**
Related to https://github.com/yarnpkg/yarn/issues/5840

### CODE REVIEW

**Comment by ai** [comment]
It looks like an overkill for me. I do not see the real problems of lock file mutation to add a special script to fix it.

But you can change my mind by showing the actual problem of these mutations.

**Comment by pustovalov** [comment]
successful build after `yarn install`
https://travis-ci.com/pustovalov/size-limit/jobs/282419158
https://github.com/pustovalov/size-limit/commit/c8d751a046b07e4de883cf0ccaf9790859524a60

**Comment by pustovalov** [comment]
This is not a significant problem but everyone else who wants to do a PR for this repo, will be confused: 
Why am I modifying `yarn.lock` file? I didn’t change anything

As was with me in this PR:
https://github.com/ai/size-limit/pull/155/files

**Comment by ai** [comment]
I have the same system for all my open source projects. Adding extra script will be too much. Sorry.

**Pull request closed without merging**
