### PR TITLE
Fix ignore option.

### PR DESCRIPTION
**Pull request by jaydenseric**
Fixes https://github.com/ai/size-limit/issues/68.

I rushed this fix and haven't tested it much.

### CODE REVIEW

**Comment by ai** [comment]
You need to escape strings in RegExp.

**Comment by jaydenseric** [comment]
What do you mean? I used the same RegExp you already had…

```diff
   if (opts.ignore && opts.ignore.length !== 0) {
     let escaped = opts.ignore.map(i => escapeRegexp(i))
-    let regexp = new RegExp(`^(${ escaped.join('|') })($|/)`)
-    config.plugins.push(new webpack.IgnorePlugin(regexp))
+    config.externals = new RegExp(`^(${ escaped.join('|') })($|/)`)
   }
```

You have push access, so feel free to add polish 😌

I'm pretty desperate for the fix though; the current published version is broken.

**Comment by ai** [comment]
> What do you mean? I used the same RegExp you already had…

What is `escaped` will contain some RegExp control symbols? Like `escaped = 'one.two'`, the result will be `^(one.two)($|/)` which will match to `oneBtwo`, since `.` is any symbol in RegExp.

**Comment by ai** [comment]
> You have push access, so feel free to add polish relieved

OK

**Comment by ai** [comment]
Oops, my mistake. You already escaped string above. :+1:

**Comment by ai** [comment]
Released in 0.19.2

**Pull request merged**
