### PR TITLE
Add import option to check config

### PR DESCRIPTION
**Pull request by bschlenk**
This option allows specifying a specific exported object to be imported
from the configured path, allowing testing for tree shaking.

Closes ~~https://github.com/ai/size-limit/issues/161~~ https://github.com/ai/size-limit/issues/111

TODOs:

- [ ] documentation
- [ ] config validation?
- [ ] verify sizes reported by test

### CODE REVIEW

**Comment by ai** [comment]
1. Yeap, we need docs. Can I ask you to add docs as an English native speaker?
2. We can miss config validation for now.
3. Sizes in the test look good. But you can replace `AAAAA` to some random symbols, it will make a size difference in test bigger.

**Comment by bschlenk** [comment]
1. Sure, I'll update with some docs when I get the time.
2. I can tackle this too - the only validation I can think of is that if import is used, then path cannot be an array
3. Would that be to reduce the amount of gzip compression?

**Comment by ai** [comment]
> Would that be to reduce the amount of gzip compression?

Yeap, `AAAA` is doing good for gzip compression, so we do not see a big difference in `methodA` and `methodB`.

**Comment by ai** [comment]
I forced feature because I need it for my open-source which uses [`dual-publish`](https://github.com/ai/dual-publish/)

**Comment by bschlenk** [comment]
This wasn’t ready yet. Doesn’t support default import.

**Comment by ai** [comment]
I added docs and default import. It was easy. You did a main work.

**Pull request merged**
