### PR TITLE
fix: allow esbuild config properties

### PR DESCRIPTION
**Pull request by angeloashmore**
This PR allows esbuild options to be set, including the `config` and `modifyEsbuildConfig` options.

Without this PR, Size Limit will halt upon entry validation since `config` and `modifyEsbuildConfig` have not be marked as valid options.

### Reproduction

See: https://github.com/angeloashmore/size-limit-esbuild-config-repro

### CODE REVIEW

**Comment by ai** [comment]
Thanks. I will try to release it today if CI will pass.

**Comment by ai** [comment]
Can you update snapshots?

**Comment by angeloashmore** [comment]
Absolutely! Done.

**Comment by ai** [comment]
Released in 8.0.1

**Pull request merged**
