### PR TITLE
Render both parsed and gzip sizes

### PR DESCRIPTION
**Pull request by TrySound**
Here's new size output

screen shot 2018-03-05 at 7 36 21 pm
screen shot 2018-03-05 at 7 37 08 pm
screen shot 2018-03-05 at 7 37 57 pm

### CODE REVIEW

**Comment by ai** [comment]
You should write a better description.

What is a reason for it?

**Comment by TrySound** [comment]
Gzip is good for loading. But the cost of javascript parsing make sense too. It would be good to have both values in the same place with nicer labels without double bundling.

**Comment by ai** [comment]
But it will confuse users what size is used for limit check. Also, this project goal is to prevent bloating by working in Travis CI.

Most of users will not see parsed size. And most of size bloating issue will bloat both gzip and parsed sizes.

So this UI changes for my point of view will not improve tool.

**Comment by TrySound** [comment]
To distinct target I painted parsed as grey. Probably we can add this feature to unlimited mode? It doesn't have limits and works only as info tool. However I still think this is a good use case when you work on size improvements.

**Comment by ai** [comment]
We will have the same problem in unlimited mode. This mode is used to detect limit. But if unlimited mode will report two different sizes, it will confuse users (what size I should use in the limit).

> However I still think this is a good use case when you work on size improvements.

In this case, you can have two limits with `gzip: false` and without.

**Comment by TrySound** [comment]
Can't focus help?
screen shot 2018-03-05 at 8 13 00 pm

**Comment by ai** [comment]
Nope. It is still harder to explain in docs and harder for users.

**Comment by ai** [comment]
Image yourself going to shop:

> What is a price for milk?
> 10

> What is a price for milk?
> 10 and 20
> What? Why you give me 2 prices? What is a difference between them? What I should use?

**Comment by TrySound** [comment]
When I go to the shop for milk I actually see two prices
> Price: $10
> $7 is the price with our bonus card

**Comment by ai** [comment]
Yeap, any many users complain about it, because they made a mistake ;)

**Comment by ai** [comment]
> you can have two limits with gzip: false and without.

Will this solution cover your use case?

**Comment by TrySound** [comment]
I mentioned that this requires to write more descriptive names and spend more time to bundle twice.
I just think size-limit can give wow effect for other developers when somebody tweaks their babel config. Also it could be like debugging tool when you are looking for difference between runs.

**Comment by TrySound** [comment]
What do you think about the second cli? Something like `size-info`, which will skip gzip and limit options and just show info for everything.

**Comment by ai** [comment]
Second CLI is not compatible with `npx`. But I am OK with extra option like `size-limit --info`.

**Comment by ai** [comment]
Maybe `--sizes` option is better. But how it will work together with `gzip: true/false`. Maybe we need to change it too.

**Comment by TrySound** [comment]
I think gzip false may be skipped. What else can we show?

**Comment by ai** [comment]
What do you mean by “skipped”?

**Pull request closed without merging**
