### PR TITLE
Fixed note while using file plugin with enabled gzip

### LINKED ISSUE #185: Using size-limit with just `file` plugin doesn't output `gzipped` as note
It seems that there is no `gzip` plugin referenced in https://github.com/ai/size-limit/blob/3571e79736a5cd7bf9cf245ff7d5ea2e3ac5f9ef/packages/size-limit/create-reporter.js#L86-L87, isn't it? Just guess that in this check we need to have something like `plugins.has('file') && check.gzip !== false`?

### PR DESCRIPTION
**Pull request by timocov**
Fixes #185

### CODE REVIEW

**Comment by ai** [comment]
Can you update snapshots by calling `npx jest -u`?

**Comment by timocov** [comment]
Yeah, I'm in the process... It was self-confidently to trying to fix it in without checking out the code by modifying a file right on GitHub 😂

**Comment by timocov** [comment]
I'm not sure how the failed tests are related to this PR. Can you help me with that please?

**Comment by ai** [comment]
I re-run the tests and they passed. Seems like it was a random issue.

**Comment by ai** [comment]
I will think we will release it together with a fix for https://github.com/ai/size-limit/issues/184

**Pull request merged**
