### PR TITLE
Update Webpack to v4.

### PR DESCRIPTION
**Pull request by jaydenseric**
Fixes [#41](https://github.com/ai/size-limit/issues/41):

- Updated Webpack dependency to v4.0.0-beta.2.
- Updated Webpack related dependencies for the Yarn lock file.
- In the changelog fixed capitalization of “Webpack” everywhere and ran Prettier.

### CODE REVIEW

**Comment by jaydenseric** [comment]
Tested it using `npm link`, and it seems ok:

screen shot 2018-02-21 at 1 02 08 pm

The warning is harmless, some packages are waiting for a stable v4 before adopting the new API and webpack will still support the old for a while.

I looked into all the webpack related dependencies and I could not see anything that would break moving to Webpack v4.

**Comment by ai** [comment]
@jaydenseric do you have this warning without `--why`?

**Comment by jaydenseric** [comment]
Yes.

**Comment by ai** [comment]
Could you please revert ChangeLog changes? ;) If you want to change format, it should be in the different PR.

**Comment by jaydenseric** [comment]
The changelog formatting matches the same way you have the readme formatted; new lines under headings.

**Comment by ai** [comment]
1. The warning should be from `WebpackBundleAnalyzer`. It is an only plugin added on `--why`.
2. In README.md I also have double new lines at the end of a section. I am not sure that we should copy this format to ChangeLog. Format purposes are different.

**Comment by ai** [comment]
Seems like you also need to fix tests, Webpack 4 changes sizes.

**Comment by jaydenseric** [comment]
Feel free to add commits to get this PR across the line, I don't have this project open anymore and am too busy ATM to work out the tests and things to see it through 🙂

**Comment by ai** [comment]
@jaydenseric don’t worry. I will finish it over the weekend. Can I only ask you to revert ChangeLog changes, because if I accept this PR (to fix tests), git history will be tricky?

**Comment by ai** [comment]
I created issue about depreacted warning:

https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/154

Also I should think on weekends about using Webpack’s `mode` instead of manually set UglifyJS.

**Comment by ai** [comment]
I made a PR to Webpack Bundle Analyzer. Since warning is showing in any Size Limit mode, I need to wait for this PR (or Size Limit tests will fail).

**Comment by ai** [comment]
PR to `uglify-webpack-plugin` was sent too https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/238

**Comment by ai** [comment]
PR to `compression-webpack-plugin` was sent too https://github.com/webpack-contrib/compression-webpack-plugin/pull/100

**Comment by ai** [comment]
All PRs were accepted. I manually took changes from this commit https://github.com/ai/size-limit/commit/aca11bf9dc78ca5f045e5c94021c157900811c2d

**Comment by ai** [comment]
Released in 0.15.

**Pull request closed without merging**
