### PR TITLE
Getting plugins from local node_modules

### PR DESCRIPTION
**Pull request by ahtohbi4**
Presets are looked for starting from the current folder (the current working directory of the process) and going down to the root to be sure of primary using the ones from local `node_modules`.

### CODE REVIEW

**Comment by ai** [comment]
Great. Thanks. I will release it next day, because I have a flight today.

**Comment by ai** [comment]
I will try to make release on weekend, there are a lot of dependencies changes

**Comment by ai** [comment]
Released in 2.1.3

**Comment by ahtohbi4** [comment]
Thanks! I hope that it will be useful for someone. 😉

**Pull request merged**
