### PR TITLE
Ignore peer dependencies with multiple entries in why mode

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by ai** [comment]
> No description provided

:man_facepalming: 

Can you explain better what you try to fix there and why?

**Comment by TrySound** [comment]
`why` mode has condition with one size-limit entry in package.json and more than one entries. Currently `ignore` is not passed in the second case even if peerDependencies are present, so when I try to run `why` with esm and cjs entries I get peer dependency in the bundle.

**Comment by TrySound** [comment]
What do you think?

**Comment by ai** [comment]
Oops, I forgot about it =^_^=

**Comment by ai** [comment]
Released in 0.16.2.

**Pull request merged**
