### PR TITLE
Add explicit `packageManager` field to `package.json`

### PR DESCRIPTION
**Pull request by aryaemami59**
## **This PR:**

- [X] Adds explicit `packageManager` field to `package.json`.

### CODE REVIEW

**Comment by ai** [comment]
I have 50+ open source projects, it will be very hard for me keep up to date to version of pnpm in package.json manually in every project.

Do you have any reason why this key is important to spend more time on maintenance?

**Comment by ai** [comment]
I really afraid of locking the exact version of pnpm.

What if there is old project with 9.1.1 and new developer come with 9.2? Will it require too many versions of pnpm on developers machine in corepack?

**Comment by aryaemami59** [comment]
In that case, they will already have version 9.1.1 on their machine, since corepack caches the old versions on the global registry, and will not remove them unless they call `corepack cache clear` manually.

**Comment by ai** [comment]
I decided to not use it right now. It is better to use the latest pnpm.

**Pull request closed without merging**
