### PR TITLE
Add mobx-state-tree case

### PR DESCRIPTION
**Pull request by pustovalov**
https://github.com/mobxjs/mobx-state-tree/pull/1292

### CODE REVIEW

**Comment by ai** [comment]
The rules about the Users section. It should be a very big project or good minification step (like −20% of the size).

I have this rule to keep section clear and focused (a big list is worse than small with few most important items).

**Comment by pustovalov** [comment]
Ok then, how is a very big project determined?

**Comment by ai** [comment]
I think it will be better for you just to reduce `mobx-state-tree` size and use % in this section.

Anyway “X uses Size Limit” is just hype driven development. Size Limit should be useful.

**Comment by pustovalov** [comment]
Ok, thx

**Pull request closed without merging**
