### PR TITLE
Add Material-UI

### PR DESCRIPTION
**Pull request by oliviertassinari**
great project

### CODE REVIEW

**Comment by ai** [comment]
Awesome! :)

**Comment by oliviertassinari** [comment]
capture d ecran 2017-07-13 a 18 23 22

**Comment by ai** [comment]
For such big project — yeap. But it is always good idea to make it smaller :D.

**Comment by oliviertassinari** [comment]
We have done some effort in that direction lately. I don't want to see any regression :). Thanks for sharing this project.

**Pull request merged**
