### PR TITLE
Yarn 2 support

### PR DESCRIPTION
**Pull request by pustovalov**
Related to https://github.com/ai/size-limit/issues/154

### CODE REVIEW

**Comment by ai** [comment]
CI fails because `packages/size-limit/create-help.js:89` line was not covered with tests

**Comment by ai** [comment]
Do we need a major release? Or it will just print warning?

**Comment by pustovalov** [comment]
It will print a warning, if user doesn’t have a size-limit in dev dependencies 
https://github.com/ai/size-limit/pull/156/files#diff-ba32842adaed10794b6c66a24aaea6a4R120

**Comment by pustovalov** [comment]
Do we still need this dependency?
https://github.com/ai/size-limit/blob/master/packages/file/package.json#L21

**Comment by ai** [comment]
Released at 3.0.1.

Yeap, seems like we forget to move `size-limit` from `dependencies` to `peerDependencies`. Can you send another PR?

**Comment by ai** [comment]
I will fix `dependencies`

**Pull request merged**
